/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xingchang_jni_aes256_demo_JniUtil */

#ifndef _Included_com_example_xingchang_jni_aes256_demo_JniUtil
#define _Included_com_example_xingchang_jni_aes256_demo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xingchang_jni_aes256_demo_JniUtil
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xingchang_jni_1aes256_1demo_JniUtil_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_xingchang_jni_aes256_demo_JniUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xingchang_jni_1aes256_1demo_JniUtil_decrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
